changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: bug
      labels:
        - bug
    - title: documentation
      labels:
        - documentation
        - duplicate
    - title: duplicate
      labels:
        - duplicate
    - title: Other Changes
      labels:
        - "*"
