changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: bug
      labels:
        - bug
        - bar
    - title: foo
      labels:
        - foo
    - title: documentation
      labels:
        - documentation
        - duplicate
    - title: duplicate
      labels:
        - duplicate
    - title: enhancement
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
    
