name: merge-test

on:
  workflow_dispatch:

jobs:
  printLog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
      - name: Checkout master branch
        run: git checkout master
      - name: Merge develop into master
        run: |
          git merge develop
          if [ $? -ne 0 ]; then
            echo "Merge conflict detected. Aborting."
            exit 1
          fi
      - name: Push changes to master
        run: git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
