name: merge-test

on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  meme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: develop
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
      - name: Checkout main branch
        run: git checkout main
      - name: Merge develop into main
        run: |
          git merge develop
          if [ $? -ne 0 ]; then
            echo "Merge conflict detected. Aborting."
            exit 1
          fi
      - name: Push changes to main
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
